  - tw: 1
    conditions:
      - start_hour: 7
        end_hour: 14
        season: high
        work_day: true
      - start_hour: 16
        end_hour: 20
        season: high
        work_day: true
  - tw: 2
    conditions:
      - start_hour: 6
        end_hour: 7
        season: high
        work_day: true
      - start_hour: 14
        end_hour: 16
        season: high
        work_day: true
      - start_hour: 20
        end_hour: 22
        season: high
        work_day: true
      - start_hour: 7
        end_hour: 14
        season: high
        work_day: false
      - start_hour: 16
        end_hour: 20
        season: high
        work_day: false
      - start_hour: 7
        end_hour: 14
        season: low
        work_day: true
      - start_hour: 16
        end_hour: 20
        season: low
        work_day: true
  - tw: 3
    conditions:
      - start_hour: 0
        end_hour: 6
        season: high
        work_day: true
      - start_hour: 22
        end_hour: 24
        season: high
        work_day: true
      - start_hour: 6
        end_hour: 7
        season: high
        work_day: false
      - start_hour: 14
        end_hour: 16
        season: high
        work_day: false
      - start_hour: 20
        end_hour: 22
        season: high
        work_day: false
      - start_hour: 6
        end_hour: 7
        season: low
        work_day: true
      - start_hour: 14
        end_hour: 16
        season: low
        work_day: true
      - start_hour: 20
        end_hour: 22
        season: low
        work_day: true
      - start_hour: 7
        end_hour: 14
        season: low
        work_day: false
      - start_hour: 16
        end_hour: 20
        season: low
        work_day: false
  - tw: 4
    conditions:
      - start_hour: 0
        end_hour: 6
        season: high
        work_day: false
      - start_hour: 22
        end_hour: 24
        season: high
        work_day: false
      - start_hour: 0
        end_hour: 6
        season: low
        work_day: true
      - start_hour: 22
        end_hour: 24
        season: low
        work_day: true
      - start_hour: 6
        end_hour: 7
        season: low
        work_day: false
      - start_hour: 14
        end_hour: 16
        season: low
        work_day: false
      - start_hour: 20
        end_hour: 22
        season: low
        work_day: false
  - tw: 5
    conditions:
      - start_hour: 0
        end_hour: 6
        season: low
        work_day: false
      - start_hour: 22
        end_hour: 24
        season: low
        work_day: false